"""add voice_catalog table

Revision ID: a65fcd8fef1d
Revises: 6945045eafae
Create Date: 2026-05-30 05:23:38.166608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a65fcd8fef1d'
down_revision: Union[str, Sequence[str], None] = '6945045eafae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voice_catalog',
    sa.Column('voice_id', sa.String(length=64), nullable=False, comment='CosyVoice 返回的 voice_id'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='用户起的名字，如「耿同学」'),
    sa.Column('language', sa.String(length=10), nullable=False, comment='语言代码：zh / en / ...'),
    sa.Column('gender', sa.String(length=10), nullable=True, comment='male / female / neutral'),
    sa.Column('created_by', sa.Uuid(), nullable=True, comment='创建者 user_id（审计用途，非权限控制主键）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标志'),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('voice_id')
    )
    op.create_index(op.f('ix_voice_catalog_language'), 'voice_catalog', ['language'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voice_catalog_language'), table_name='voice_catalog')
    op.drop_table('voice_catalog')
    # ### end Alembic commands ###
